gameFeatures:
  enabled: true
  pistons: true
  hoppers: true
  packedIceInHell: false
  villagerTrading: false
  shulkerBoxUse: false
  enderChestUse: false
  enderChestPlacement: true
  disableElytraFirework: true
  preventFallingThroughBedrock: true
ctAnnounce:
  enabled: true
  delay: 10000
  message: "&4%Victim% was combat tagged by %Attacker%"
chunkLimits:
  enabled: true
  message: "&9You've exceeded the chunk limit for that block type!"
  limits:
    REDSTONE_DUST: 16
    PISTON_BASE: 10
    STICKY_PISTON_BASE: 10
    HOPPER: 16
    OBSERVER: 2
daytimeBed:
  enabled: true
  message: "&7Your spawn has been set."
raiderAnnounce:
  enabled: true
  message: "&4%Name% is raiding a chest at %X%, %Y%, %Z%."
  delay: 10000
newfriendAssist:
  enabled: true
  message: "&6%Name% is new to the server!"
  newfriendKit:
    cookie:
      material: COOKIE
      name: Manna
      lore:
      - A gift from the admins as you begin your journey on Civ
      amount: 64
    bed:
      material: BED
      amount: 1
    