gameFeatures:
  enabled: true
  pistons: true
  hoppers: true
  packedIceInHell: false
  villagerTrading: false
  shulkerBoxUse: false
  enderChestUse: false
  enderChestPlacement: true
ctAnnounce:
  enabled: true
  delay: 10000
  message: '%Victim% was combat tagged by %Attacker%'