name: ${name}
version: ${version}
main: ${groupId}.${name}
author: Soer
softdepend: [CombatTagPlus]

permissions:
  bumhug.*:
    description: Gives all Bumhug permissions
    default: op
    children:
      bumhug.broadcastCombat: true
  bumhug.broadcastCombat:
    description: Receive broadcasts when a player is combat-tagged
    default: op
  bumhug.reloadInventory:
    description: Reload a player's inventoy from before the last time they died
    default: op

commands:
  reloadinventoy:
    description: Reload a player's inventoy from before the last time they died
    permission: bumhug.reloadInventory
    usage: /reloadinventory [playername:UUID]