name: ${name}
version: ${version}
main: ${groupId}.${name}
author: Soer
softdepend: [CombatTagPlus, Citadel]

permissions:
  bumhug.*:
    description: Gives all Bumhug permissions
    default: op
    children:
      bumhug.broadcastCombat: true
  bumhug.broadcastCombat:
    description: Receive broadcasts when a player is combat-tagged
    default: op
  bumhug.bypassChunkLimits:
    description: Place blocks in chunks that have exceeded the chunk limit for that type of block
    default: op
  bumhug.broadcastRaiding:
    description: Receive broadcasts when a player is breaking a reinforced chest
    default: op